name: ACCD
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100c09'
    - '#2b221b'
    - '#594838'
    - '#a76940'
    - '#e0c192'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: 198a3205-f0fb-4f38-b436-e453fb610949
    url: null
