name: ACCD
favicon: null
layout_spectrum: 0.43882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#452b18'
    - '#d1cbc4'
    - '#837163'
    - '#a2958d'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
