name: ACCD
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100c09'
    - '#2b221b'
    - '#594838'
    - '#a76940'
    - '#e0c192'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: 31f30138-7847-490c-936d-a8028fe5c2af
    url: null
